'use client';

import { FormEvent, useState } from 'react';

export function SuggestForm() {
  const [result,setResult]=useState<{id?:string;status?:string;message?:string;error?:string}|null>(null);const [saving,setSaving]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setResult(null);const form=event.currentTarget;const data=new FormData(form);try{const response=await fetch('/api/submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({problem:data.get('problem'),people:data.get('people'),currentToday:data.get('currentToday'),frequency:data.get('frequency'),better:data.get('better'),existingTool:data.get('existingTool'),companyWebsite:data.get('companyWebsite'),safetyConfirmed:data.get('safetyConfirmed')==='on'})});const payload=await response.json();setResult(payload);if(response.ok)form.reset();}catch{setResult({error:'The intake service is unavailable. Nothing was saved.'});}finally{setSaving(false)}}
  return <><form className="intake-form" onSubmit={submit}><div className="demo-label">PUBLIC SUBMISSION · PRIVATE SAFETY REVIEW</div><label>What problem do you see?<textarea name="problem" required minLength={20} maxLength={500} placeholder="Describe a recurring problem using public, non-sensitive information."/></label><div className="form-row"><label>Who experiences it?<input name="people" required maxLength={160} placeholder="A general group—not a person, unit, or location"/></label><label>How often?<select name="frequency" defaultValue=""><option value="" disabled>Choose one</option><option>Occasionally</option><option>Monthly</option><option>Weekly</option><option>Daily</option><option>Not sure</option></select></label></div><label>What happens today?<textarea name="currentToday" required minLength={10} maxLength={500} placeholder="Explain the current public process or workaround without identifying people or internal systems."/></label><label>What would better look like?<textarea name="better" required minLength={10} maxLength={320} placeholder="Describe the outcome, not necessarily a feature."/></label><label>Existing public tool or process (optional)<input name="existingTool" maxLength={240} placeholder="Name or public URL only"/></label><label className="honeypot-field" aria-hidden="true">Company website<input name="companyWebsite" tabIndex={-1} autoComplete="off"/></label><label className="check-label"><input name="safetyConfirmed" type="checkbox" required/><span>I confirm this contains only publicly released, non-sensitive information and no personal, unit, readiness, operational, credential, or internal-system details.</span></label><button className="button" type="submit" disabled={saving}>{saving?'Saving…':'Send for safety review'}</button><p className="form-note">No account is required. The full entry stays private until a steward approves a public brief.</p></form>{result&&<div className={`submission-result ${result.error?'submission-error':''}`} role="status"><strong>{result.error?'Nothing was saved':`${result.id} · ${result.status}`}</strong><p>{result.error??result.message}</p></div>}</>;
}
