export const toolCatalog = [
  { id:'afi-explorer',name:'AFI Explorer', category:'Publications', platform:'Web · iOS · Android', ownership:'External independent project', maintainer:'Drew Stephens / William Walker', source:'DAF e-Publishing', repositoryStatus:'Public repository available', license:'MIT for Android; iOS license not verified', huhyRole:'Discovery listing only', lifecycle:'Degraded signal', maintenance:'Maintainer activity observed', website:'https://afiexplorer.com/', github:'https://github.com/drewstephensdesigns/AFIExplorer', note:'Official publications remain canonical.',evidenceAsOf:'2026-08-24' },
  { id:'dsn-converter',name:'DSN Converter', category:'Communications', platform:'Web', ownership:'External Airmen Coders project', maintainer:'Airmen Coders', source:'Public directory data', repositoryStatus:'Public repository available', license:'MIT', huhyRole:'Discovery and potential upstream contribution', lifecycle:'Aging indication', maintenance:'Status needs verification', website:'https://dsn-converter.pages.dev/', github:'https://github.com/airmencoders/DSN-Converter', note:'The project remains with its existing owner.',evidenceAsOf:'2026-08-24' },
  { id:'my-air-force-benefits',name:'MyAirForceBenefits', category:'Benefits', platform:'Web', ownership:'External official service', maintainer:'Department of the Air Force', source:'Official authority', repositoryStatus:'No public repository identified', license:'Government service; code license not identified', huhyRole:'Authority link only', lifecycle:'Active signal', maintenance:'Department of the Air Force', website:'https://myairforcebenefits.us.af.mil/', github:null, note:'Use the official service for benefit determinations.',evidenceAsOf:'2026-08-24' },
  { id:'military-fitness-calc',name:'Military Fitness Calc', category:'Fitness', platform:'Web', ownership:'External independent project', maintainer:'Not identified', source:'Governing source displayed', repositoryStatus:'No public repository identified', license:'Not identified', huhyRole:'Discovery listing only', lifecycle:'Active signal', maintenance:'Unknown', website:'https://www.militaryfitnesscalc.com/air-force-pt-calculator.html', github:null, note:'Visible source provenance; accuracy has not been independently verified.',evidenceAsOf:'2026-08-24' },
  { id:'terminal-leave-calculator',name:'Terminal Leave Calculator', category:'Leave', platform:'Spreadsheet', ownership:'External government-hosted resource', maintainer:'Not identified', source:'Scott AFB-hosted file', repositoryStatus:'No public repository identified', license:'Not identified', huhyRole:'Discovery listing only', lifecycle:'Review needed', maintenance:'Unknown', website:'https://www.scott.af.mil/Portals/28/Attachment%203_%20Terminal%20Leave%20Calculator.xlsx', github:null, note:'Formula and guidance date need verification.',evidenceAsOf:'2026-08-24' },
  { id:'sofa-gas-buddy',name:'SOFA Gas Buddy', category:'Overseas benefits', platform:'Android', ownership:'External independent project', maintainer:'CyberAustin / 4DLolz', source:'AAFES ESSO website interaction', repositoryStatus:'Public source available', license:'CC BY-NC 4.0; not OSI open source', huhyRole:'Discovery and maintainer referral', lifecycle:'Maintainer wanted', maintenance:'Successor needed', website:'https://play.google.com/store/apps/details?id=com.cyberaustin.sofagasbuddy', github:'https://github.com/SOFAGasBuddy/sofa_gas_buddy', note:'High account-data sensitivity and a noncommercial license require caution.',evidenceAsOf:'2026-08-24' },
  { id:'aflink',name:'AFLink', category:'Directories', platform:'Web', ownership:'External independent project', maintainer:'dadatuputi', source:'Owner-curated public repository and link submissions', repositoryStatus:'Public repository available', license:'MIT', huhyRole:'Discovery and potential upstream contribution', lifecycle:'Active signal', maintenance:'Repository activity observed 25 Aug 2026', website:'https://aflink.us/', github:'https://github.com/dadatuputi/aflink', note:'Includes official and unofficial links; each destination keeps its own access and information rules.',evidenceAsOf:'2026-08-25' },
];

export const externalProjectCatalog = [
  { id:'afi-explorer',name:'AFI Explorer',summary:'Open Android app for finding and reading Air Force publications.',owner:'Drew Stephens / AFI Explorer contributors',github:'https://github.com/drewstephensdesigns/AFIExplorer',repositoryStatus:'Active repository',license:'MIT',contributionSignal:'README welcomes issues and pull requests.',lastActivity:'1 Aug 2026',risk:'Medium',note:'DAF e-Publishing remains authoritative; publication ingestion and answer accuracy require verification.',evidenceAsOf:'25 Aug 2026' },
  { id:'aflink',name:'AFLink',summary:'Accessible directory for USAF links with community-submitted corrections.',owner:'dadatuputi',github:'https://github.com/dadatuputi/aflink',repositoryStatus:'Active repository',license:'MIT',contributionSignal:'Issue forms accept link additions, overrides, and deletions.',lastActivity:'25 Aug 2026',risk:'Medium',note:'The directory mixes official and unofficial destinations; verify every link and its access boundary.',evidenceAsOf:'25 Aug 2026' },
  { id:'sofa-gas-buddy',name:'SOFA Gas Buddy',summary:'Android client for interacting with the AAFES ESSO fuel-ration service.',owner:'SOFA Gas Buddy contributors',github:'https://github.com/SOFAGasBuddy/sofa_gas_buddy',repositoryStatus:'PRs welcome',license:'CC BY-NC 4.0; not an OSI software license',contributionSignal:'Repository README says pull requests are welcome.',lastActivity:'29 Jan 2026',risk:'High',note:'Account and personal data are involved. Confirm license terms and maintainer continuity before work.',evidenceAsOf:'25 Aug 2026' },
];
