'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';

type Recommendation={id:string;name:string;website:string;repository:string|null;category:string;relationship:string;useCase:string;maintainer:string|null;license:string|null;reviewNotes:string|null;status:string;decisionNote:string|null;listedToolId:string|null;createdAt:string};
const statuses=['Pending review','Listed','Duplicate','Referred to owner','Not listed'];
async function readJson(response:Response){const payload=await response.json();if(!response.ok)throw new Error(payload.error);return payload}

export function ToolRecommendationQueue(){
  const [records,setRecords]=useState<Recommendation[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const payload=await fetch('/api/tool-recommendations',{cache:'no-store'}).then(readJson);setRecords(payload.recommendations??[]);setError('')}catch(error){setError(error instanceof Error?error.message:'Unable to load tool recommendations.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void fetch('/api/tool-recommendations',{cache:'no-store'}).then(readJson).then((payload)=>{setRecords(payload.recommendations??[]);setError('')}).catch((error:unknown)=>setError(error instanceof Error?error.message:'Unable to load tool recommendations.')).finally(()=>setLoading(false))},[]);
  async function save(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setSaving(id);setError('');setNotice('');const data=new FormData(event.currentTarget);try{const payload=await fetch(`/api/tool-recommendations/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:data.get('status'),decisionNote:data.get('decisionNote')})}).then(readJson);setNotice(payload.message);await load()}catch(error){setError(error instanceof Error?error.message:'Unable to save the recommendation.')}finally{setSaving('')}}
  return <section className="recommendation-queue"><div className="queue-heading"><div><p className="eyebrow">TOOL RECOMMENDATIONS</p><h2>Review before listing</h2></div><span>{records.filter((record)=>record.status==='Pending review').length} pending</span></div>{notice&&<p className="submission-result" role="status">{notice}</p>}{error&&<p className="submission-result submission-error" role="alert">{error}</p>}{loading&&<p className="empty-state">Loading tool recommendations…</p>}{!loading&&!records.length&&<p className="empty-state">No tool recommendations yet.</p>}<div className="recommendation-list">{records.map((record)=><article className="recommendation-card" key={record.id}><div><span>{record.id} · {record.status}</span><h3>{record.name}</h3><small>{record.category} · {record.relationship}</small></div><p>{record.useCase}</p><dl><div><dt>Tool</dt><dd><a href={record.website} target="_blank" rel="noreferrer">{record.website} ↗</a></dd></div>{record.repository&&<div><dt>Repository</dt><dd><a href={record.repository} target="_blank" rel="noreferrer">{record.repository} ↗</a></dd></div>}<div><dt>Maintainer</dt><dd>{record.maintainer||'Not identified'}</dd></div><div><dt>Claimed license</dt><dd>{record.license||'Not identified'}</dd></div>{record.reviewNotes&&<div><dt>Suggested review</dt><dd>{record.reviewNotes}</dd></div>}{record.listedToolId&&<div><dt>Directory record</dt><dd>{record.listedToolId}</dd></div>}</dl>{record.status!=='Listed'&&<form className="recommendation-disposition" onSubmit={(event)=>save(event,record.id)}><label>Disposition<select name="status" defaultValue={record.status}>{statuses.map((status)=><option key={status}>{status}</option>)}</select></label><label>Review reason<textarea name="decisionNote" maxLength={500} defaultValue={record.decisionNote??''} placeholder="Required when leaving the pending queue"/></label><button className="button button-small" disabled={saving===record.id}>{saving===record.id?'Saving…':'Save recommendation'}</button></form>}</article>)}</div></section>;
}
