'use client';

import { useEffect, useMemo, useState } from 'react';
import { toolCatalog } from '../data';

type Tool=typeof toolCatalog[number]&{ratingAverage:number|null;ratingCount:number;userRating:number|null};

export function ToolDirectory() {
  const [query,setQuery]=useState('');const [category,setCategory]=useState('All categories');const [tools,setTools]=useState<Tool[]>(toolCatalog.map((tool)=>({...tool,ratingAverage:null,ratingCount:0,userRating:null})));const [message,setMessage]=useState('');const [saving,setSaving]=useState('');const [signedIn,setSignedIn]=useState(false);
  useEffect(()=>{fetch('/api/tools',{cache:'no-store'}).then(async(response)=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);setTools(payload.tools);setSignedIn(payload.signedIn===true)}).catch(()=>setMessage('Live ratings are unavailable; the research catalog is still shown.'))},[]);
  const filtered=useMemo(()=>tools.filter((tool)=>(category==='All categories'||tool.category===category)&&`${tool.name} ${tool.category} ${tool.note} ${tool.ownership} ${tool.maintainer}`.toLowerCase().includes(query.toLowerCase())),[tools,query,category]);
  async function rate(id:string,stars:number){setSaving(id);setMessage('');try{const response=await fetch(`/api/tools/${id}/rating`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({stars})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setTools((items)=>items.map((tool)=>tool.id===id?{...tool,...payload}:tool));setMessage('Your usefulness rating was saved.');}catch(error){setMessage(error instanceof Error?error.message:'The rating could not be saved.')}finally{setSaving('')}}
  return <><div className="tool-controls"><label><span>Search the Air Force tool research catalog</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Try leave, publications, fitness, benefits…"/></label><label><span>Air Force life area</span><select value={category} onChange={(event)=>setCategory(event.target.value)}><option>All categories</option>{[...new Set(tools.map((tool)=>tool.category))].map((item)=><option key={item}>{item}</option>)}</select></label></div>{message&&<p className="rating-message" role="status">{message}</p>}{!signedIn&&<p className="rating-signin">Want to rate a tool? <a href="/signin-with-chatgpt?return_to=/tools">Sign in with ChatGPT</a>. Ratings measure usefulness only.</p>}<div className="tool-grid">{filtered.map((tool)=><article className="tool-card" key={tool.id}><div className="tool-card-top"><span>{tool.category}</span><span>RESEARCH CATALOG · {tool.evidenceAsOf}</span></div><span className="ownership-badge">NOT A HUHY-OWNED TOOL</span><h3>{tool.name}</h3><p className="tool-owner">{tool.ownership}</p><div className="tool-rating"><strong>{tool.ratingCount?`${Number(tool.ratingAverage).toFixed(1)} / 5`:'No community ratings yet'}</strong>{tool.ratingCount>0&&<span>({tool.ratingCount})</span>}</div><fieldset className="rating-input" disabled={!signedIn||saving===tool.id}><legend>{signedIn?'Rate community usefulness—not safety or approval':'Sign in to rate usefulness'}</legend>{[1,2,3,4,5].map((star)=><button key={star} type="button" className={star<=(tool.userRating??0)?'selected':''} onClick={()=>rate(tool.id,star)} aria-label={`Rate ${tool.name} ${star} out of 5`}>★</button>)}</fieldset><p>{tool.note}</p><dl><div><dt>Owner / maintainer</dt><dd>{tool.maintainer}</dd></div><div><dt>Repository</dt><dd>{tool.repositoryStatus}</dd></div><div><dt>Observed license</dt><dd>{tool.license}</dd></div><div><dt>HUHY role</dt><dd>{tool.huhyRole}</dd></div><div><dt>Reference authority</dt><dd>{tool.source}</dd></div><div><dt>Lifecycle</dt><dd>{tool.lifecycle}</dd></div><div><dt>Maintenance</dt><dd>{tool.maintenance}</dd></div><div><dt>Platform</dt><dd>{tool.platform}</dd></div></dl><div className="tool-destinations">{tool.website&&<a href={tool.website} target="_blank" rel="noreferrer">Open owner&apos;s tool ↗</a>}{tool.github&&<a href={tool.github} target="_blank" rel="noreferrer">Open owner&apos;s repository ↗</a>}</div></article>)}</div>{!filtered.length&&<p className="empty-state">No tools match those filters.</p>}</>;
}
